# Generated by Django 4.1.7 on 2023-04-01 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_rapper_profile_image_rapper_social_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapper', to=settings.AUTH_USER_MODEL),
        ),
    ]
