# Generated by Django 4.1.7 on 2023-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_rapper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapper',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
