# Generated by Django 4.1.7 on 2023-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rapper_email_rapper_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapper',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
