# Generated by Django 4.1.7 on 2023-04-02 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
