# Generated by Django 4.1.7 on 2023-04-14 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandations',
            fields=[
                ('recommandations', models.TextField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rapper')),
            ],
        ),
    ]
