# Generated by Django 4.1.7 on 2023-04-14 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_recommandations_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandations',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recommandations',
            unique_together={('owner', 'rapper')},
        ),
    ]
