# Generated by Django 4.1.7 on 2023-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_recommandations_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapper',
            name='recommendations',
        ),
    ]
