# Generated by Django 4.1.7 on 2023-04-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_rapper_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandations',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_recommendations', to='home.rapper'),
        ),
        migrations.AlterField(
            model_name='recommandations',
            name='rapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to='home.rapper'),
        ),
    ]
