# Generated by Django 4.1.7 on 2023-04-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_recommandations_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommandations',
            unique_together=set(),
        ),
    ]
