# Generated by Django 4.1.7 on 2023-04-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_recommandations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommandations',
            unique_together={('owner', 'rapper')},
        ),
    ]
