# Generated by Django 4.1.7 on 2023-04-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_rapper_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandations',
            name='competition',
        ),
    ]
