# Generated by Django 4.1.7 on 2023-04-17 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_recommandations_unique_together'),
        ('competition', '0004_alter_competition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.competition')),
                ('rapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='home.rapper')),
                ('recommandations', models.ManyToManyField(related_name='recommandations_for_comp', to='home.recommandations')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='home.song')),
            ],
        ),
    ]
