# Generated by Django 4.1.7 on 2023-04-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_remove_competitionentry_recommandations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionentry',
            name='song',
        ),
    ]
